name: vrt

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: app install
        run: |
          sudo apt-get install -y software-properties-common
          sudo apt-get update
          sudo add-apt-repository -y ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install -y git
      - name: Checkout syonet_eight
        uses: actions/checkout@v2
        with:
          repository: igara/syonet_eight
          token: ${{ github.token }}
          submodules: true
      - name: Checkout submodule
        run: |
          git submodule update --init --remote projects/syonet_eight_design_system
          (cd projects/syonet_eight_design_system && git checkout master && git pull)
          git submodule update --init --remote projects/syonet_eight_www
          (cd projects/syonet_eight_www && git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*" && git fetch && git checkout ${{ github.ref_name }})
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install task
        run: |
          yarn
      - name: run reg-suit
        run: |
          yarn build:storybook:www
          yarn storycap:www
          yarn vrt:www

env:
  REG_NOTICE_CLIENT_ID: ${{ secrets.REG_NOTICE_CLIENT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
